apiVersion: apps/v1
kind: Deployment
metadata:
  name: lowcoder-ce-api-service
  labels:
    app: lowcoder-ce-api-service
  namespace: cityos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lowcoder-ce-api-service
  template:
    metadata:
      labels:
        name: lowcoder-ce-api-service
        app: lowcoder-ce-api-service
    spec:
      containers:
        - name: lowcoder-ce-api-service
          image: lowcoderorg/lowcoder-ce-api-service:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: PUID
            value: "9001"
          - name: PGID
            value: "9001"
          - name: MONGODB_URL
            value: "mongodb://ioc2023:Ioc%232023@192.168.88.66:27017/lowcoder?authSource=admin"
          - name: REDIS_URL
            value: "redis://192.168.88.90:9379"
          - name: LOWCODER_NODE_SERVICE_URL
            value: "http://lowcoder-ce-node-service-svc:6060"
          - name: LOWCODER_MAX_QUERY_TIMEOUT
            value: "120"
          - name: ENABLE_USER_SIGN_UP
            value: "true"
          - name: ENCRYPTION_PASSWORD
            value: "lowcoder.org"
          - name: ENCRYPTION_SALT
            value: "lowcoder.org"
          - name: CORS_ALLOWED_DOMAINS
            value: "*"
          - name: DEFAULT_ORGS_PER_USER
            value: "100"
          - name: DEFAULT_ORG_MEMBER_COUNT
            value: "1000"
          - name: DEFAULT_ORG_GROUP_COUNT
            value: "100"
          - name: DEFAULT_ORG_APP_COUNT
            value: "1000"
          - name: DEFAULT_DEVELOPER_COUNT
            value: "50"
          - name: LOWCODER_API_KEY_SECRET
            value: "5a41b090758b39b226603177ef48d73ae9839dd458ccb7e66f7e7cc028d5a50b"
          ports:
          - containerPort: 8080
            protocol: TCP
      restartPolicy: Always