apiVersion: v1
kind: Service
metadata:
  name: lowcoder-ce-frontend-svc
  labels:
    app: lowcoder-ce-frontend-service
  namespace: cityos
spec:
  type: NodePort
  ports:
    - name: app
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 9393
  selector:
    app: lowcoder-ce-frontend